// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqVFezK9HNE4lQEHwFxZNchFhkQg9Cm-A',
    appId: '1:822653346569:web:67e56a8f0218c7216929d8',
    messagingSenderId: '822653346569',
    projectId: 'aviturismo-92a64',
    authDomain: 'aviturismo-92a64.firebaseapp.com',
    storageBucket: 'aviturismo-92a64.firebasestorage.app',
    measurementId: 'G-R9Q7Y092PE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABtXe-T3z-ayIJBUynHUgjukzAvFH_ujg',
    appId: '1:822653346569:android:7b10981575f6e7fc6929d8',
    messagingSenderId: '822653346569',
    projectId: 'aviturismo-92a64',
    storageBucket: 'aviturismo-92a64.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTpyTYP6T9SpHAcMrIZB8piSinGitf5D0',
    appId: '1:822653346569:ios:9357b5b7e6ada6806929d8',
    messagingSenderId: '822653346569',
    projectId: 'aviturismo-92a64',
    storageBucket: 'aviturismo-92a64.firebasestorage.app',
    iosBundleId: 'com.example.appZoologico',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTpyTYP6T9SpHAcMrIZB8piSinGitf5D0',
    appId: '1:822653346569:ios:9357b5b7e6ada6806929d8',
    messagingSenderId: '822653346569',
    projectId: 'aviturismo-92a64',
    storageBucket: 'aviturismo-92a64.firebasestorage.app',
    iosBundleId: 'com.example.appZoologico',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqVFezK9HNE4lQEHwFxZNchFhkQg9Cm-A',
    appId: '1:822653346569:web:831ef8efb97ae2556929d8',
    messagingSenderId: '822653346569',
    projectId: 'aviturismo-92a64',
    authDomain: 'aviturismo-92a64.firebaseapp.com',
    storageBucket: 'aviturismo-92a64.firebasestorage.app',
    measurementId: 'G-EDKKE8TGFX',
  );

}