name: fronted
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  boxicons: ^2.1.1
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  image_picker_web: ^2.0.0
  http: ^0.13.4 #  solicitudes HTTP
  shared_preferences: ^2.1.0 


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
